import { EB_Garamond } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";

const font = EB_Garamond({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header/>
        <div className="pt-20">{children}</div>
      </body>
    </html>
  );
}
